echo OSTAVETE GO PROZORECOT OTVOREN DODEKA RABOTITE SO BAZATA
echo PRED DA GO STARTUVATE OVA PRVIOT PAT SMENETE JA LOZINKATA I PORTATA
echo VO ONIE KOI VI SE DADENI VO UPATSTVATA
echo SLUSHA NA 9999, smenete LOZINKA
plink -ssh -2 -C -N -L 9999:localhost:5432 -pw tunelot2019 tunnelvezhbi@bazi.finki.ukim.mk
